name: Actualizar Noticias Diariamente

on:
  schedule:
    # 09:00 UTC equivale a las 06:00 AM en Argentina (UTC-3)
    - cron: '0 9 * * *'
  workflow_dispatch: # Sigue permitiendo la ejecución manual por si quieres forzar una actualización

permissions:
  contents: write

jobs:
  ejecutar-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install feedparser

      - name: Ejecutar todos los scripts de scraping
        run: |
          python politica-argentina.py
          python economia-argentina.py
          python politica-internacional.py
          python futbol-argentino.py
          python autos.py
          python economica-internacional.py
          python futbol-europeo.py
          python futbol-africano.py
          python motos.py

      - name: Hacer commit y push de los nuevos archivos JSON
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # "git add ." detectará automáticamente todas las carpetas nuevas y los JSON de hoy
          git add .
          
          # Realiza el commit. Si por algún motivo un día falla una extracción, el script no se rompe
          git commit -m "Automatización: Extracción diaria de noticias completada" || echo "Sin cambios para commitear"
          
          git push